site_name: Antares
repo_url: https://github.com/AntaresSimulatorTeam/antares-doc
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logos/logo.png
  favicon: assets/logos/icone.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.top
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: src/index.md
  - Overview:
    - Antares suite:
      - Use Cases: src/overview/use-cases.md
      - Products: src/overview/product-comparison.md
      - Architecture: src/overview/architecture.md
    - Release notes: src/overview/changelogs.md
    - Forum & support: src/overview/forum-and-support.md
    - Roadmap: src/overview/roadmap.md
    - Research: src/overview/bibliography.md
    - Licenses: src/overview/licenses.md
    - Glossary: src/overview/glossary.md
  - Getting started:
    - Installation:
      - Desktop installation: src/getting-started/install-desktop.md
      - Base installation: src/getting-started/install-base.md
      - Performance installation: src/getting-started/install-performance.md
    - First steps:
      - Import study: src/getting-started/import-study.md
      - Explore data: src/getting-started/explore-data.md
      - Launch simulation: src/getting-started/launch-simulation.md
      - Read outputs: src/getting-started/read-outputs.md
  - Interface:
      - Sidebar: src/interface/sidebar.md
      - Navigation: src/interface/navigation.md
      - Configuration: src/interface/config.md
      - Outputs: src/interface/outputs.md
      - Shortcuts: src/interface/shortcuts.md
      - Table Mode: src/interface/table-mode.md
      - XPansion: src/interface/xpansion.md
  - Tutorials:
    - Create links: src/tutorials/create-links.md
    - Manage studies:
      - Import study: src/tutorials/import-study.md
      - Export study: src/tutorials/export-study.md
      - Data management: src/tutorials/data-management.md
      - Create variant: src/tutorials/create-variant.md
    - Modelling:
      - Set binding constraint: src/tutorials/set-binding-constraint.md
      - Set additional constraints on short-term storage: src/tutorials/set-constraint-st-storage.md
      - Set load: src/tutorials/set-load.md
      - Build scenario: src/tutorials/build-scenario.md
    - GEMS: src/tutorials/gems.md
    - Xpansion:
      - Define candidates: src/tutorials/define-candidates.md
      - Invest on a cluster: src/tutorials/invest-cluster.md
      - Invest on a link: src/tutorials/invest-link.md
      - Set the parameters: src/tutorials/invest-parameters.md
      - Analyze outputs: src/tutorials/invest-outputs.md
    - Productivity:
      - Modify TS: src/tutorials/modify-ts.md
    - Random Seeds: src/tutorials/random-seeds.md
    - Reduce Output: src/tutorials/reduce-output.md
    - Outputs:
      - Visualize Raw: src/tutorials/visualize-raw.md
      - Visualize by Area: src/tutorials/vizualize-by-area.md
      - Visualize by Variable: src/tutorials/vizualize-by-variable.md
  - Reference:
    - Fundamentals:
      - Problem: src/technicals/problem.md
      - Hypothesis: src/technicals/hypothesis.md
    - Inputs: src/technicals/inputs.md
    - Grid modelling:
      - Area: src/technicals/area.md
      - Link: src/technicals/link.md
      - Load: src/technicals/load.md
      - Thermal: src/technicals/thermal.md
      - Renewables: src/technicals/renewables.md
      - Run of river: src/technicals/ror.md
      - Long-term storage: src/technicals/storage-long.md
      - Short-term storage: src/technicals/storage-short.md
      - Binding constraints: src/technicals/binding-constraints.md
    - Solver:
      - At glance: src/technicals/solver-at-glance.md
      - Solver parameters: src/technicals/solver-parameters.md
      - Optimization: src/technicals/optimization.md
    - Optimization problem:
      - Optimization theory: src/technicals/optimization-problem.md
      - Flow models: src/technicals/flow-models.md
      - Random and epsilon parameters: src/technicals/random-and-epsilon-parameters.md
    - Adequacy patch: src/technicals/adequacy-patch.md
    - Output: src/technicals/output-structure.md
    - Xpansion:
      - Introduction: src/technicals/xpansion-intro.md
      - Theory: src/technicals/xpansion-theory.md
  - Contributing:
    - Code Guidelines: src/contributing/guidelines-code.md
    - Documentation Guidelines: src/contributing/guidelines-docs.md
    - Local Editing: src/contributing/local-editing.md
    - Online Editing: src/contributing/online-editing.md

plugins:
  - search
  - drawio:
      darkmode: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  # mathjax integration
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # - https://code.jquery.com/jquery-3.6.0.min.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  # - https://viewer.diagrams.net/js/viewer-static.min.js
  # - javascripts/drawio-reload.js

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys

copyright: Copyright &copy; 2007 - 2026 RTE
