site_name: Antares
repo_url: https://github.com/AntaresSimulatorTeam/antares-doc
edit_uri: edit/main/docs/
docs_dir: docs

theme:
  name: material
  logo: assets/logos/logo.png
  favicon: assets/logos/icone.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.top
    # - navigation.sections
    # - navigation.tabs
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Overview:
    - Use Cases: src/overview/use-cases.md
    - Products: src/overview/product-comparison.md
    - Architecture: src/overview/architecture.md
    - Release notes: src/overview/changelogs.md
    - Forum & support: src/overview/forum-and-support.md
    - Roadmap: src/overview/roadmap.md
  - Getting started:
    - Installation:
      - Desktop installation: src/getting-started/install-desktop.md
      - Base installation: src/getting-started/install-base.md
      - Performance installation: src/getting-started/install-performance.md
    - First steps: src/getting-started/first-steps.md
  - Interface:
      - Sidebar: src/interface/sidebar.md
      - Navigation: src/interface/navigation.md
      - Configuration: src/interface/config.md
      - Outputs: src/interface/outputs.md
      - Shortcuts: src/interface/shortcuts.md
      - Table Mode: src/interface/table-mode.md
      - XPansion: src/interface/xpansion.md
  - Tutorials:
    - Create links: src/tutorials/create-links.md
    - Manage studies:
      - Import a study: src/tutorials/import-study.md
      - Export study: src/tutorials/export-study.md
      - Data management: src/tutorials/data-management.md
      - Create a variant: src/tutorials/create-variant.md
      - Use table mode: src/tutorials/use-table-mode.md
    - Modelling:
      - Set binding constraints: src/tutorials/set-binding-constraint.md
      - Set additional constraints on short-term storage: src/tutorials/set-constraint-st-storage.md
      - Set load: src/tutorials/set-load.md
      - Build scenario: src/tutorials/build-scenario.md
    - GEMS: src/tutorials/gems.md
    - Invest with Xpansion:
      - Define candidates: src/tutorials/define-candidates.md
      - Invest on a cluster: src/tutorials/invest-cluster.md
      - Invest on a link: src/tutorials/invest-link.md
      - Set the parameters: src/tutorials/invest-parameters.md
      - Analyze outputs: src/tutorials/invest-outputs.md
    - Productivity:
      - Modify TS: src/tutorials/modify-ts.md
    - Random Seeds: src/tutorials/random-seeds.md
    - Reduce Output: src/tutorials/reduce-output.md
    - Outputs:
      - Visualize Raw: src/tutorials/visualize-raw.md
      - Visualize by Area: src/tutorials/vizualize-by-area.md
      - Visualize by Variable: src/tutorials/vizualize-by-variable.md
    - Debug your study: src/tutorials/debug-your-study.md
  - Reference:
    - Modelling:
      - Area: src/reference/area.md
      - Link: src/reference/link.md
      - Load: src/reference/load.md
      - Thermals: src/reference/thermals.md
      - Storages: src/reference/storages.md
      - Renewables: src/reference/renewables.md
      - Hydro: src/reference/hydro.md
      - Reserves: src/reference/reserves.md
      - Misc. gen.: src/reference/misc-gen.md
      - Binding constraints: src/reference/binding-constraints.md
    - Configuration:
      - General: src/reference/config-general.md
      - Time-series generation: src/reference/config-ts-generation.md
      - Optimization: src/reference/config-optimization.md
      - Adequacy patch: src/reference/config-adequacy-patch.md
      - Advanced parameters: src/reference/config-advanced-parameters.md
      - Economic options: src/reference/config-economic-options.md
      - Geographic trimming: src/reference/config-geographic-trimming.md
    - Table mode: src/reference/table-mode.md
    - Adequacy patch: src/reference/adequacy-patch.md
    - Outputs: src/reference/outputs.md
    - Xpansion:
      - Introduction: src/reference/xpansion-intro.md
      - Theory: src/reference/xpansion-theory.md
      - Candidates: src/reference/xpansion-candidates.md
      - Settings: src/reference/xpansion-settings.md
      - Constraints: src/reference/xpansion-constraints.md
      - Weights: src/reference/xpansion-weights.md
      - Capacities: src/reference/xpansion-capacities.md
    - Debug: src/reference/debug.md
    - Mathematical formulation:
      - Hypothesis: src/reference/hypothesis.md
      - Optimization problem: src/reference/optimization-problem.md
      - Flow models: src/reference/flow-models.md
      - Random and epsilon parameters: src/reference/random-and-epsilon-parameters.md
      - Hydro heuristic: src/reference/hydro-heuristic.md
      - Thermal heuristic: src/reference/thermal-heuristic.md
      - Water values: src/reference/water-values.md
    - Bibliography: src/reference/bibliography.md
    - Glossary: src/reference/glossary.md
  - Contributing:
    - Code Guidelines: src/contributing/guidelines-code.md
    - Documentation Guidelines: src/contributing/guidelines-docs.md
    - Local Editing: src/contributing/local-editing.md
    - Online Editing: src/contributing/online-editing.md

plugins:
  - search
  - drawio:
      darkmode: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  # mathjax integration
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # - https://code.jquery.com/jquery-3.6.0.min.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  # - https://viewer.diagrams.net/js/viewer-static.min.js
  # - javascripts/drawio-reload.js

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys

copyright: Copyright &copy; 2007 - 2026 RTE
